spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_task
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create